name: telephone
description: "`telephone` offers a simplified wrapper around `sip_ua` for Flutter, facilitating seamless integration of SIP-based VoIP capabilities with customizable widgets for handling call interfaces and states efficiently."
version: 0.0.1
homepage: https://github.com/igorkurilenko/telephone

environment:
  sdk: ^3.5.3
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.2.0
  logger: ^2.6.0
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.0
  sip_ua:
    git:
      url: https://github.com/4ternity/dart-sip-ua.git
      ref: fix/web-js-interop
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: